#
# Configuration for Travis CI
# ---------------------------
# Author: Malik Zharykov
#
before_install:
  - wget ${KALKAN_XMLDSIG_DOWNLOAD_URL} -O ./lib
  - wget ${KALKAN_DOWNLOAD_URL} -O ./lib
install:
  - mvn clean
script:
  - mvn package