language: java
dist: trusty
jdk:
- oraclejdk8
install:
- wget ${KALKAN_DOWNLOAD_URL} -P ./lib
- wget ${KALKAN_XMLDSIG_DOWNLOAD_URL} -P ./lib
- mvn install:install-file -Dfile=./lib/kalkancrypt-0.6.jar -DgroupId=pki.gov.kz -DartifactId=kalkancrypt
  -Dversion=0.6 -Dpackaging=jar -DgeneratePom=true
- mvn install:install-file -Dfile=./lib/kalkancrypt_xmldsig-0.3.jar -DgroupId=pki.gov.kz
  -DartifactId=kalkancryptxmldsig -Dversion=0.3 -Dpackaging=jar -DgeneratePom=true
script:
- mvn package
after_success:
- NCANODE_BUILD_VERSION=${TRAVIS_TAG:1:100}
- 'echo "Build version is: ${NCANODE_BUILD_VERSION}"'
- "./build_release.sh $NCANODE_BUILD_VERSION"
deploy:
  provider: releases
  api_key:
    secure: FF2oJs1Zpyx3GOxjrCako/r4lDQRC3kbuOKmKyfa8nw5r6SHs4I0IGeCKUTNLUuw3FWhNk8cCnZKnTm6CT0BSaxf6kAxn9bc3IN8CBINwn/l6l8I2aO46xOGipOqmwqrj+XgdXAF9HuYwGXC/iM7zDksaJ2bpEqbc64GFxQKXXK1S4nEDea+t5JZUVkyCWNzjJX/+zyhUHBPeW6fSIbyRHag6GOnHurVOJ1idS5L2OMNkQ1ut2sO/8ZCuTDf6MFU/O34FGJi5i1bioJJ8rCCg04QynkndGLNkzGBP8D18Np1Qs57iNEAzBBWxsHRpR8g1Ych6f9XKn8TglDrFcBMRIEJCPecG04WQV3lzI00o7/E/jhy26AiOIxq60d+n4rOi2I21EBZ3Cfx2Z04ptKjNYDpvT70iCnnAn94mfBIToSvgdhcuBitQNct2/uKZuHtF59ukLoWXQVc+6LpR60d2wBucQ1RZGIZZNx73/q3qs+GAEd6v5ogNZw/TdDQTeTnAZomBYlW+b9TiVy0lGTmhZrQbikDqfLF56sUmVq7tBoVC8h/B+hUqsx75suC808XuSG58s2U5EeIHMZ9iXm/ZNTHPnC897gdqSjvSqdcK4gcCSAbqSo8WELnc8BB9Sna+7OzAgFtNA2z8PK8Me0VHUzqSeKliykF6RX9bMxxkZY=
  file_glob: true
  file:
    - "NCANode*.zip"
    - "NCANode*.tar.gz"
  on:
    tags: true
  skip_cleanup: 'true'
