language: java
dist: trusty
jdk:
- oraclejdk8
install:
- wget ${KALKAN_DOWNLOAD_URL} -P ./lib
- wget ${KALKAN_XMLDSIG_DOWNLOAD_URL} -P ./lib
- mvn install:install-file -Dfile=./lib/kalkancrypt-0.6.jar -DgroupId=pki.gov.kz -DartifactId=kalkancrypt
  -Dversion=0.6 -Dpackaging=jar -DgeneratePom=true
- mvn install:install-file -Dfile=./lib/kalkancrypt_xmldsig-0.3.jar -DgroupId=pki.gov.kz
  -DartifactId=kalkancryptxmldsig -Dversion=0.3 -Dpackaging=jar -DgeneratePom=true
script:
- mvn package
after_success:
- NCANODE_BUILD_VERSION=${TRAVIS_TAG:1:100}
- 'echo "Build version isx: ${NCANODE_BUILD_VERSION}"'
- "./build_release.sh $NCANODE_BUILD_VERSION"
deploy:
  provider: releases
  api_key:
    secure: KCPYj9jKO3eXxDtWjrogppCC+Emo5hiSAByDwAfPNnlYS3P+9To/KUh46Wu6b6Tm/lUmu/doMFxW9x7teKJ20h44GBJ15U7jRDQrr2tCU+wXKRsSO+ODBV7WDh9s1jsGQQrbGIE2Mz+AdBskbw1QkFvYyDk8tNyrsP3uBcPeg7mgneqMbbNd/Tmt7/9TAnsjBGZ9JMTflYQC9AlZmb5bHKRdT2Xh2gpzwmlK27dGNPTj+F1pnsUEF21Qzb4hAMZsq/wxpcBcYoesytblVr6gj34QzQjghARMsHJdjCn31b+Pt+UECx4pexXiU0vhFOrdtrrWA77ujK7/KUp2/K0ZMqcc94kgvPAh28a6dmJdQOCqkhkLmzuHaqga/JDiVgoANDU9KoRbO/cNk3m/Jp/v7+hkyAPCWOUP1FNfIkegCbX0URIOiv/6T0O0xZgkwTCnjh/lBazWuQPGOpHy+ErzIecroKjXhXXormKQi/z+ipNaYA3SW34dzyUVUvNn/wtkpVv+KPMBjCViiBWdW5UCcAA+RMCjhEectMcFNKoyVlKKqPXjBTMYwIIkfaPp5mVmsEJRDMpLVeVrRti1CxVRvgeA/CbqvMIswTNWIfOr1sHFSS9VUdu0R/nUEd9WvqHEP25eZJQBDj06FEJuYggc0zG49hvmcy5VqIsxFv91bWk=
  file_glob: true
  file:
    - "NCANode*.tar.gz"
    - "NCANode*.zip"
  on:
    tags: true
  skip_cleanup: 'true'
  draft: true
