language: java
dist: trusty
jdk:
  - oraclejdk8
install:
  - wget ${KALKAN_DOWNLOAD_URL} -P ./lib
  - wget ${KALKAN_XMLDSIG_DOWNLOAD_URL} -P ./lib
  - mvn install:install-file -Dfile=./lib/kalkancrypt-0.6.jar -DgroupId=pki.gov.kz -DartifactId=kalkancrypt -Dversion=0.6 -Dpackaging=jar -DgeneratePom=true
  - mvn install:install-file -Dfile=./lib/kalkancrypt_xmldsig-0.3.jar -DgroupId=pki.gov.kz -DartifactId=kalkancryptxmldsig -Dversion=0.3 -Dpackaging=jar -DgeneratePom=true
script:
  - mvn package